### ISSUE TITLE
authorization error

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Freddywhest/RockyRabbitBot#10]
At first the bot worked fine, but after a while I saw the following error on every session.
**Restarting the bot solved the problem**, but I still have to report it.
```
[2024-08-29 22:37:55] | INFO | x | 📡 Waiting for authorization...
[2024-08-29 22:37:55] | ERROR | Unhandled error while receiving data
TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be
read with ID 1294139288. Most likely, a TLObject was trying to be read when
it should not be read. Remaining bytes: 556
at BinaryReader.tgReadObject (/home/RockyRabbitBot/node_modules/telegram/extensions/BinaryReader.js:195:31)
at VirtualClass.readResult (/home/RockyRabbitBot/node_modules/telegram/tl/api.js:451:35)
at MTProtoSender._handleRPCResult (/home/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:554:44)
at MTProtoSender._processMessage (/home/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:476:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async MTProtoSender._recvLoop (/home/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:424:17) {
invalidConstructorId: 1294139288,
remaining: <Buffer 98 ff 22 4d 01 00 00 00 65 9e e3 11 0a 2b 6f 2c 02 00 68 74 74 70 73 3a 2f 2f 70 6c 61 79 2e 72 6f 63 6b 79 72 61 62 62 69 74 2e 69 6f 2f 23 74 ... 506 more bytes>
}
[2024-08-29 22:37:55] | ERROR | x | ❗Unknown error during Authorization: Error: Could not find a matching Constructor ID for the TLObject that was supposed to be
read with ID 1294139288. Most likely, a TLObject was trying to be read when
it should not be read. Remaining bytes: 556
[2024-08-29 22:37:55] | INFO | x | 🚀 Starting session...
[2024-08-29 22:37:55] | ERROR | x | ❗Unknown error: Error: Could not find a matching Constructor ID for the TLObject that was supposed to be
read with ID 1294139288. Most likely, a TLObject was trying to be read when
it should not be read. Remaining bytes: 556}
[2024-08-29 22:37:55] | INFO | x | Sleeping for 110 seconds...
```

**Comment by Nord1cWarr1or** [comment]
it's repeated several times in a row.

**Comment by Freddywhest** [comment]
1. What's your nodejs version?
2. Have you installed the packages?

**Comment by Nord1cWarr1or** [comment]
I was using version 22.x, but after the last update the bot wouldn't start, and wrote me that it only works on version 18 or 20. I uninstalled version 22, and installed 20.x, deleted the bot and installed it again, and of course I installed the packages.

**Comment by Nord1cWarr1or** [comment]
By the way, this error didn't bother me today, but yesterday it repeated several times after restarting the bot.

**Comment by Nord1cWarr1or** [comment]
The error appears again from time to time. It appears simultaneously on all sessions, and does not go away until I restart the bot.

```
[2024-09-02 07:55:24] | INFO | x | 📡 Waiting for authorization...
[2024-09-02 07:55:24] | ERROR | Unhandled error while receiving data
TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be
read with ID 1294139288. Most likely, a TLObject was trying to be read when
it should not be read. Remaining bytes: 552
at BinaryReader.tgReadObject (/home/tgbots/RockyRabbitBot/node_modules/telegram/extensions/BinaryReader.js:195:31)
at VirtualClass.readResult (/home/tgbots/RockyRabbitBot/node_modules/telegram/tl/api.js:451:35)
at MTProtoSender._handleRPCResult (/home/tgbots/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:554:44)
at MTProtoSender._processMessage (/home/tgbots/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:476:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async MTProtoSender._recvLoop (/home/tgbots/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:424:17) {
invalidConstructorId: 1294139288,
remaining: <Buffer 98 ff 22 4d 01 00 00 00 3a dc a7 15 e6 0e 43 35 fe 13 02 00 68 74 74 70 73 3a 2f 2f 61 79 2e 72 6f 63 6b 79 72 61 62 62 69 74 2e 69 6f 2f 23 74 ... 502 more bytes>
}
[2024-09-02 07:55:24] | ERROR | x | ❗Unknown error during Authorization: Error: Could not find a matching Constructor ID for the TLObject that was supposed to be
read with ID 1294139288. Most likely, a TLObject was trying to be read when
it should not be read. Remaining bytes: 552
[2024-09-02 07:55:24] | INFO | x | 🚀 Starting session...
[2024-09-02 07:55:24] | ERROR | x | ❗Unknown error: Error: Could not find a matching Constructor ID for the TLObject that was supposed to be
read with ID 1294139288. Most likely, a TLObject was trying to be read when
it should not be read. Remaining bytes: 552}
[2024-09-02 07:55:24] | INFO | x | Sleeping for 97 seconds...
```

**Comment by Freddywhest** [comment]
Update to the latest version and try again. It should work

**Comment by Nord1cWarr1or** [comment]
I'll be watching to see if the error reappears

**Comment by Freddywhest** [comment]
No further comments, so I'll assume it's working and close this issue

**Comment by Nord1cWarr1or** [comment]
@Freddywhest 
Now the error has reappeared again.
```
[2024-09-07 11:46:49] | ERROR | Unhandled error while receiving data
TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be
read with ID 1294139288. Most likely, a TLObject was trying to be read when
it should not be read. Remaining bytes: 584
at BinaryReader.tgReadObject (/home/tgbots/RockyRabbitBot/node_modules/telegram/extensions/BinaryReader.js:195:31)
at VirtualClass.readResult (/home/tgbots/RockyRabbitBot/node_modules/telegram/tl/api.js:451:35)
at MTProtoSender._handleRPCResult (/home/tgbots/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:554:44)
at MTProtoSender._processMessage (/home/tgbots/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:476:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async MTProtoSender._recvLoop (/home/tgbots/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:424:17) {
invalidConstructorId: 1294139288,
remaining: <Buffer 98 ff 22 4d 01 00 00 00 55 40 ab a5 eb a1 87 36 fe 33 02 00 74 70 73 3a 2f 2f 70 6c 61 79 2e 72 6f 63 6b 79 72 61 62 62 69 74 2e 69 6f 2f 23 74 ... 534 more bytes>
}
[2024-09-07 11:46:49] | ERROR | [rockyrabbit] | x | ❗Unknown error during Authorization: Error: Could not find a matching Constructor ID for the TLObject that was supposed to be
read with ID 1294139288. Most likely, a TLObject was trying to be read when
it should not be read. Remaining bytes: 584
[2024-09-07 11:46:50] | INFO | [rockyrabbit] | x | Sleeping for 108 seconds..
```

**Comment by Freddywhest** [comment]
How long was it running **continuously** before you encountered this error?

**Comment by Nord1cWarr1or** [comment]
Since my last post, that is about 4 days.

**Comment by Freddywhest** [comment]
I updated the repo two days ago. Update it and try again. If you encounter this error again, restart the bot. After extensive research, I found that this error isn't related to the script but rather to the Telegram library I'm using, and they haven't fixed it yet

**Comment by Nord1cWarr1or** [comment]
Okay, thank you !
