### ISSUE TITLE
Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by mrdarkerr** [Freddywhest/RockyRabbitBot#17]
node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /root/RockyRabbitBot/bot/config/config.js
- /root/RockyRabbitBot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/root/RockyRabbitBot/bot/config/config.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/RockyRabbitBot/bot/config/config.js',
    '/root/RockyRabbitBot/index.js'
  ]
}

**Comment by Freddywhest** [comment]
Refer to the README file and follow the steps provided to install this script
