### ISSUE TITLE
Getting this runtime error

### ISSUE THREAD

**Issue by bowler14** [Freddywhest/RockyRabbitBot#34]
[2024-09-11 17:34:37] | ERROR | Unhandled error while receiving data
TypeError: Cannot read properties of undefined (reading 'readUInt32LE')
      at BinaryReader.readInt (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/extensions/BinaryReader.js:37:31)
      at BinaryReader.tgReadObject (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/extensions/BinaryReader.js:165:36)
      at MTProtoSender._handleRPCResult (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:532:30)
      at MTProtoSender._processMessage (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:478:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MTProtoSender._handleContainer (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:575:13)
      at async MTProtoSender._processMessage (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:478:9)
      at async MTProtoSender._recvLoop (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/network/MTProtoSender.js:426:17)
TypeError: Cannot use 'in' operator to search for 'phoneNumber' in undefined
      at _authFlow (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/client/auth.js:362:30)
      at Object.start (/home/hero/Desktop/TG_Bot/RockyRabbitBot/node_modules/telegram/client/auth.js:45:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async #get_tg_web_data (/home/hero/Desktop/TG_Bot/RockyRabbitBot/bot/core/tapper.js:104:7)
      at async Tapper.run (/home/hero/Desktop/TG_Bot/RockyRabbitBot/bot/core/tapper.js:257:31)
      at async /home/hero/Desktop/TG_Bot/RockyRabbitBot/bot/utils/luncher.js:1:7998
      at async Promise.all (index 12)
      at async #run_tasks (/home/hero/Desktop/TG_Bot/RockyRabbitBot/bot/utils/luncher.js:1:8141)
      at async Luncher.process (/home/hero/Desktop/TG_Bot/RockyRabbitBot/bot/utils/luncher.js:1:5601)
      at async main (/home/hero/Desktop/TG_Bot/RockyRabbitBot/index.js:22:5)
[2024-09-11 17:34:37] | ERROR | [rockyrabbit] | hero | ❗️Unknown error during Authorization: TypeError: Cannot use 'in' operator to search for 'phoneNumber' in undefined

**Comment by Freddywhest** [comment]
Create a new session
