### ISSUE TITLE
WebSocket Connection Failure

### ISSUE THREAD

**Issue by afridi315** [Freddywhest/RockyRabbitBot#4]
I am trying to run the project but it shows the following error;
```
ERROR | WebSocket connection failed attempt: 1
Error: Not connected
at ConnectionTCPFull.recv (D:\EAf\WebProjects\Node\RockyRabbitBot\node_modules\telegram\network\connection\Connection.js:71:15)
    at async MTProtoPlainSender.send (D:\EAf\WebProjects\Node\RockyRabbitBot\node_modules\telegram\network\MTProtoPlainSender.js:44:16)
    at async doAuthentication (D:\EAf\WebProjects\Node\RockyRabbitBot\node_modules\telegram\network\Authenticator.js:21:19)
    at async MTProtoSender._connect (D:\EAf\WebProjects\Node\RockyRabbitBot\node_modules\telegram\network\MTProtoSender.js:239:25)
    at async MTProtoSender.connect (D:\EAf\WebProjects\Node\RockyRabbitBot\node_modules\telegram\network\MTProtoSender.js:147:17)
    at async TelegramClient.connect (D:\EAf\WebProjects\Node\RockyRabbitBot\node_modules\telegram\client\TelegramClient.js:1065:15)
    at async Object.start (D:\EAf\WebProjects\Node\RockyRabbitBot\node_modules\telegram\client\auth.js:36:9)
    at async Register.start (D:\EAf\WebProjects\Node\RockyRabbitBot\bot\core\register.js:65:5)
```
please help!

**Comment by Freddywhest** [comment]
Check your network
